### ISSUE TITLE
NPE if no extracted span context

### ISSUE THREAD

**Issue by malafeev** [opentracing-contrib/java-web-servlet-filter#26]
https://github.com/opentracing-contrib/java-web-servlet-filter/blob/master/opentracing-web-servlet-filter/src/main/java/io/opentracing/contrib/web/servlet/filter/TracingFilter.java#L151

if `extractedContext` is null then `.asChildOf(extractedContext)` [here](https://github.com/opentracing-contrib/java-web-servlet-filter/blob/master/opentracing-web-servlet-filter/src/main/java/io/opentracing/contrib/web/servlet/filter/TracingFilter.java#L155) can produce NPE and it does for Lightstep tracer

**Comment by objectiser** [comment]
The `asChildOf` method should be able to accept a `null`: https://github.com/opentracing/opentracing-java/blob/master/opentracing-api/src/main/java/io/opentracing/Tracer.java#L106

**Comment by malafeev** [comment]
thanks @objectiser 
will file issue against Lightstep

https://github.com/lightstep/lightstep-tracer-java/issues/108
