### ISSUE TITLE
Add JAR to maven central

### ISSUE THREAD

**Issue by zdicesare** [opentracing-contrib/java-web-servlet-filter#41]
Currently only a pom is provided.

It looks like this is the case for all versions: https://search.maven.org/search?q=a:opentracing-web-servlet-filter-parent

**Comment by zdicesare** [comment]
Ah, I was a little off here:

It looks like there's both: https://mvnrepository.com/artifact/io.opentracing.contrib/opentracing-web-servlet-filter-parent/0.1.1

and: https://mvnrepository.com/artifact/io.opentracing.contrib/opentracing-web-servlet-filter/0.1.1

That reference this repo. The latter has the jar provided.

**Comment by pavolloffay** [comment]
@zdicesare so everything is fine for you? Can I close it?

**Comment by zdicesare** [comment]
@pavolloffay Yeah sorry about this - for my knowledge, what is the purpose of the opentracing-web-servlet-filter parent artifact?
