### ISSUE TITLE
More descriptive operation names

### ISSUE THREAD

**Issue by zdicesare** [opentracing-contrib/java-web-servlet-filter#42]
Currently the span names are set to the method of the request, e.g. POST.

It would be helpful if this were something like: 'HTTP POST api/v1/foo/'
or just included the endpoint.

Alternatively, we could configure the tracer with a function that returns a span name from a request.

**Comment by pavolloffay** [comment]
Http verb as operation name is chosen on purpose. Path cannot be used as operation name because one endpoint `/user/{id}` can produce different operation names.
