### ISSUE TITLE
Include license header to each java file

### ISSUE THREAD

**Issue by skabashnyuk** [opentracing-contrib/java-web-servlet-filter#46]
It might look not very important however as far as I can
see most of the other opentracing-X project has a license as a header.
I faced with this during IP certification process when I
want to include opentracing-web-servlet-filter to Eclipse Che project.
I hope that the license in the root folder is enough for IP team. But who knows...
I can submit PR if needed.

Thoughts?

**Comment by pavolloffay** [comment]
I have no objections on adding a license header. Are you interested in submitting a PR? I would appreciate the same approach as in the API repo https://github.com/opentracing/opentracing-java.

**Comment by skabashnyuk** [comment]
@pavolloffay done
