### ISSUE TITLE
Allows clients to customize operation naming pattern

### ISSUE THREAD

**Issue by epkugelmass** [opentracing-contrib/java-web-servlet-filter#57]
Similar to https://github.com/opentracing-contrib/java-web-servlet-filter/issues/45 and https://github.com/opentracing-contrib/java-web-servlet-filter/issues/42, I'd like different operation names than are provided by this library by default.

Instead of changing the default on everybody already using the library or using a potentially high cardinality field like `requestURL`, provide an API for customizing the operation naming strategy. The java-grpc OpenTracing contrib provides a similar option: https://github.com/opentracing-contrib/java-grpc/blob/master/src/main/java/io/opentracing/contrib/grpc/OperationNameConstructor.java

I'm happy to contribute a PR.

**Comment by pavolloffay** [comment]
There is already a decorator API which can be used to change operation name https://github.com/opentracing-contrib/java-web-servlet-filter/blob/master/opentracing-web-servlet-filter/src/main/java/io/opentracing/contrib/web/servlet/filter/ServletFilterSpanDecorator.java#L37.

How would your API be different to this one?

**Comment by epkugelmass** [comment]
Thank you, I didn't realize that `io.opentracing.Span::setOperationName` existed.

**Comment by pavolloffay** [comment]
I will close this then. There should not be a need for a separate API to override the span.

If you come up with a use case feel free to reopen/comment.
