### ISSUE TITLE
Support jakarta.servlet-api 5.0.0

### ISSUE THREAD

**Issue by skabashnyuk** [opentracing-contrib/java-web-servlet-filter#69]
https://jakarta.ee/specifications/servlet/5.0/
To be able to use with Jetty 11 & Tomcat 10.
Related issue https://github.com/eclipse/che/issues/20247

**Comment by skabashnyuk** [comment]
As an alternative, it could be another set of artifacts with "jakarta.servlet" imports.

**Comment by Jef-VDD** [comment]
Any reason for closing this ticket?
